{
 "title": "Monitor(BD/BACK/PROXY)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "BD PostgreeSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Conexões Ativas com o Banco(Ao longo do tempo)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"desafio_db\", usename=\"app_desafio_user\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexões Ativas com o Banco(Agora)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"desafio_db\", usename=\"app_desafio_user\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreeSQL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  { "title": "Backend ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "API Requests(Total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{route=\"/api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Requests(Ao longo do tempo)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "http_requests_total{route=\"/api\"}",
     "legendFormat": "Requisições"
    }
   ]
  },
  {
   "title": "Latência da API (Segundos)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_version_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "Proxy Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Proxy Requests(Total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proxy Requests(Ao longo do tempo)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 15 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "Requisições" }
   ]
  },
  {
   "title": "Proxy Reverso",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  }
 ]
}